// Typed access to the same tokens for use in JS, charts, and theme packages.
export const tokens = {
  color: {
    bg: "var(--dd-color-bg)",
    bgSubtle: "var(--dd-color-bg-subtle)",
    surface: "var(--dd-color-surface)",
    surface2: "var(--dd-color-surface-2)",
    elevated: "var(--dd-color-elevated)",
    border: "var(--dd-color-border)",
    borderStrong: "var(--dd-color-border-strong)",
    text: "var(--dd-color-text)",
    muted: "var(--dd-color-muted)",
    faint: "var(--dd-color-faint)",
    primary: "var(--dd-color-primary)",
    primaryStrong: "var(--dd-color-primary-strong)",
    primarySoft: "var(--dd-color-primary-soft)",
    primaryBorder: "var(--dd-color-primary-border)",
    onPrimary: "var(--dd-color-on-primary)",
    accent: "var(--dd-color-accent)",
    accentSoft: "var(--dd-color-accent-soft)",
    success: "var(--dd-color-success)",
    successSoft: "var(--dd-color-success-soft)",
    danger: "var(--dd-color-danger)",
    dangerSoft: "var(--dd-color-danger-soft)",
    warning: "var(--dd-color-warning)",
  },
  radius: {
    xs: "var(--dd-radius-xs)",
    sm: "var(--dd-radius-sm)",
    base: "var(--dd-radius)",
    lg: "var(--dd-radius-lg)",
    xl: "var(--dd-radius-xl)",
    pill: "var(--dd-radius-pill)",
  },
  space: "var(--dd-space)",
  spacing: {
    xs: "var(--dd-space-xs)",
    sm: "var(--dd-space-sm)",
    base: "var(--dd-space)",
    lg: "var(--dd-space-lg)",
    xl: "var(--dd-space-xl)",
    "2xl": "var(--dd-space-2xl)",
  },
  font: "var(--dd-font)",
  fontMono: "var(--dd-font-mono)",
  shadow: {
    sm: "var(--dd-shadow-sm)",
    base: "var(--dd-shadow)",
    lg: "var(--dd-shadow-lg)",
    glow: "var(--dd-shadow-glow)",
  },
  ring: "var(--dd-ring)",
  gradient: {
    brand: "var(--dd-gradient-brand)",
    surface: "var(--dd-gradient-surface)",
    text: "var(--dd-gradient-text)",
    line: "var(--dd-gradient-line)",
  },
} as const

export type Tokens = typeof tokens
